name: Vercel deploy

on:
  push:
    branches:
      - main
    paths:
      # only run workflow when changes are made to these files
      - package.json
  # manual trigger
  workflow_dispatch:

jobs:
  vercel-deploy:
    name: Vercel deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Prepare API source for prod
        run: python devel/prepare_api_for_dev_prod.py prod
      - name: Set vercel.json for production
        run: cp _vercel_prod.json vercel.json
      - # Not sure why this is needed, but it is
        name: Create .vercel/project.json
        run: |
          mkdir -p .vercel
          echo '{"projectId":"${{ secrets.VERCEL_PROJECT_ID }}", "orgId":"${{ secrets.VERCEL_ORG_ID }}"}' > .vercel/project.json
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
